In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("cars24_1.csv")
df.head()

,Cars,Model,Dist,Fuel,Transmission,Registration,EMI,Price
0,2020 Maruti Swift,LXI,"32,750 km",Petrol,Manual,HR-85,"EMI ₹6,713/m*",₹4.07L₹3.80 lakh+ other charges
1,2016 Renault Kwid,RXT 0.8,"77,319 km",Petrol,Manual,UP-80,"EMI ₹3,804/m*",₹1.80L₹1.71 lakh+ other charges
2,2015 Maruti Swift,VDI ABS,"87,121 km",Diesel,Manual,HR-14,Not available on EMI,₹3.81L₹3.18 lakh+ other charges
3,2022 Maruti Swift,LXI,"66,173 km",Petrol,Manual,HR-14,"EMI ₹7,432/m*",₹4.37L₹4.21 lakh+ other charges
4,2018 Renault Kwid,RXT 0.8,"62,135 km",Petrol,Manual,UP-80,"EMI ₹2,879/m*",₹2.42L₹1.63 lakh+ other charges

In [3]:
df.dtypes

Cars            object
Model           object
Dist            object
Fuel            object
Transmission    object
Registration    object
EMI             object
Price           object
dtype: object

In [4]:
df['Manufac_Year']=df['Cars'].str[0:4]
df.head()

,Cars,Model,Dist,Fuel,Transmission,Registration,EMI,Price,Manufac_Year
0,2020 Maruti Swift,LXI,"32,750 km",Petrol,Manual,HR-85,"EMI ₹6,713/m*",₹4.07L₹3.80 lakh+ other charges,2020
1,2016 Renault Kwid,RXT 0.8,"77,319 km",Petrol,Manual,UP-80,"EMI ₹3,804/m*",₹1.80L₹1.71 lakh+ other charges,2016
2,2015 Maruti Swift,VDI ABS,"87,121 km",Diesel,Manual,HR-14,Not available on EMI,₹3.81L₹3.18 lakh+ other charges,2015
3,2022 Maruti Swift,LXI,"66,173 km",Petrol,Manual,HR-14,"EMI ₹7,432/m*",₹4.37L₹4.21 lakh+ other charges,2022
4,2018 Renault Kwid,RXT 0.8,"62,135 km",Petrol,Manual,UP-80,"EMI ₹2,879/m*",₹2.42L₹1.63 lakh+ other charges,2018

In [5]:
df['Manufac_Year']=pd.to_numeric(df['Manufac_Year'])

In [6]:
df['Cars']=df['Cars'].str[5::1]
df.head(1)

,Cars,Model,Dist,Fuel,Transmission,Registration,EMI,Price,Manufac_Year
0,Maruti Swift,LXI,"32,750 km",Petrol,Manual,HR-85,"EMI ₹6,713/m*",₹4.07L₹3.80 lakh+ other charges,2020

In [7]:
df['Dist']=df['Dist'].str.replace(",","")

In [8]:
df['Dist']=(df['Dist'].str[0:-3])

In [9]:
df['Dist']=pd.to_numeric(df['Dist'])

In [10]:
df.head(1)

,Cars,Model,Dist,Fuel,Transmission,Registration,EMI,Price,Manufac_Year
0,Maruti Swift,LXI,32750,Petrol,Manual,HR-85,"EMI ₹6,713/m*",₹4.07L₹3.80 lakh+ other charges,2020

In [11]:
df.rename(columns={'Dist':'Distance_in_km'},inplace=True)

In [12]:
df['Reg_unit']=df['Registration'].str[-2::1]

In [13]:
df['Registration']=df['Registration'].str.replace("-","")

In [14]:
df['Registration']=df['Registration'].str[0:2]

In [15]:
df.head(1)

,Cars,Model,Distance_in_km,Fuel,Transmission,Registration,EMI,Price,Manufac_Year,Reg_unit
0,Maruti Swift,LXI,32750,Petrol,Manual,HR,"EMI ₹6,713/m*",₹4.07L₹3.80 lakh+ other charges,2020,85

In [16]:
df['EMI']=df['EMI'].str[5:-1:1]

In [17]:
df['EMI']=df['EMI'].str.replace(",","")
df['EMI']=df['EMI'].str.replace("/","")

In [18]:
df.head(1)

,Cars,Model,Distance_in_km,Fuel,Transmission,Registration,EMI,Price,Manufac_Year,Reg_unit
0,Maruti Swift,LXI,32750,Petrol,Manual,HR,6713m,₹4.07L₹3.80 lakh+ other charges,2020,85

In [19]:
df['EMI']=df['EMI'].str[:-1:1]

In [20]:
df.rename(columns={'EMI':'EMI_Per_Month'},inplace=True)

In [21]:
df['EMI_Per_Month']=df['EMI_Per_Month'].replace("vailable on E",np.nan)

In [22]:
df

,Cars,Model,Distance_in_km,Fuel,Transmission,Registration,EMI_Per_Month,Price,Manufac_Year,Reg_unit
0,Maruti Swift,LXI,32750,Petrol,Manual,HR,6713,₹4.07L₹3.80 lakh+ other charges,2020,85
1,Renault Kwid,RXT 0.8,77319,Petrol,Manual,UP,3804,₹1.80L₹1.71 lakh+ other charges,2016,80
2,Maruti Swift,VDI ABS,87121,Diesel,Manual,HR,NaN,₹3.81L₹3.18 lakh+ other charges,2015,14
3,Maruti Swift,LXI,66173,Petrol,Manual,HR,7432,₹4.37L₹4.21 lakh+ other charges,2022,14
4,Renault Kwid,RXT 0.8,62135,Petrol,Manual,UP,2879,₹2.42L₹1.63 lakh+ other charges,2018,80
5,Renault Kwid,RXT 0.8,41654,Petrol,Manual,HR,2929,₹2.50L₹1.50 lakh+ other charges,2017,79
6,KIA SELTOS,HTK 1.5 PETROL,43539,Petrol,Manual,HR,13243,₹8.64L₹7.50 lakh+ other charges,2022,16
7,Maruti Swift,VDI,111698,Diesel,Manual,UP,NaN,₹2.92L₹1.98 lakh+ other charges,2014,16
8,Maruti New Wagon-R,VXI 1.2,46641,Petrol,Manual,DL,5886,₹3.33 lakh+ other charges,2019,2C
9,Honda Amaze,1.2L I-VTEC VX,63933,Petrol,Manual,DL,6690,₹4.24L₹3.79 lakh+ other charges,2018,11
10,Ford FREESTYLE,AMBIENTE 1.5 DIESEL,55165,Diesel,Manual,UP,9931,₹4.99L₹2.99 lakh+ other charges,2019,25
11,Maruti Swift,LXI (O),79321,Petrol,Manual,DL,4886,₹2.70L₹2.50 lakh+ other charges,2017,8C
12,Maruti Baleno,DELTA PETROL 1.2,67702,Petrol,Manual,HR,7142,₹3.21 lakh+ other charges,2016,26
13,Toyota Glanza,S,60527,Petrol,Manual,HR,8826,₹5.64L₹5.00 lakh+ other charges,2023,26
14,Skoda SLAVIA,AMBITION 1.0L TSI MT,78434,Petrol,Manual,HR,13492,₹11.13L₹7.64 lakh+ other charges,2022,44
15,Hyundai Grand i10,SPORTZ 1.2 KAPPA VTVT,82996,Petrol,Manual,HR,6123,₹2.75 lakh+ other charges,2016,12
16,Maruti Wagon R 1.0,LXI,87492,Petrol,Manual,HR,4580,₹2.23L₹1.38 lakh+ other charges,2014,52
17,Maruti Baleno,ALPHA PETROL 1.2,49803,Petrol,Manual,DL,7786,₹3.71L₹3.50 lakh+ other charges,2016,12
18,Tata NEXON,XZ PLUS (L) DARK EDITION,55797,Petrol,Manual,UP,12569,₹8.04L₹7.12 lakh+ other charges,2022,27
19,Honda City,1.5L I-VTEC V MT,58953,Petrol,Manual,HR,8441,₹3.79 lakh+ other charges,2016,26

In [23]:
df['EMI_Per_Month']=pd.to_numeric(df['EMI_Per_Month'])

In [26]:
df.columns

Index(['Cars', 'Model', 'Distance_in_km', 'Fuel', 'Transmission',
       'Registration', 'EMI_Per_Month', 'Price', 'Manufac_Year', 'Reg_unit'],
      dtype='object')

In [27]:
df['Price']=df['Price'].str.replace("lakh","L")

In [29]:
df["Actual_Price_in_Lakhs"]=df["Price"].apply(lambda x: x.split("L")[0].replace("₹",""))

In [38]:
df["Actual_Price_in_Lakhs"]=pd.to_numeric(df["Actual_Price_in_Lakhs"])

In [33]:
df["Discounted_Price_in_Lakhs"]=(df["Price"].apply(lambda x: x.split("L")[1].replace("₹","")))

In [36]:
df["Discounted_Price_in_Lakhs"]=df["Discounted_Price_in_Lakhs"].replace("+ other charges",np.nan)

In [37]:
df["Discounted_Price_in_Lakhs"]=df["Discounted_Price_in_Lakhs"].fillna(df['Actual_Price_in_Lakhs'])

In [39]:
df["Discounted_Price_in_Lakhs"]=pd.to_numeric(df["Discounted_Price_in_Lakhs"])

In [45]:
df.head()

,Cars,Model,Distance_in_km,Fuel,Transmission,Registration,EMI_Per_Month,Price,Manufac_Year,Reg_unit,Actual_Price_in_Lakhs,Discounted_Price_in_Lakhs,Price+Other_charges
0,Maruti Swift,LXI,32750,Petrol,Manual,HR,6713.0,₹4.07L₹3.80 L+ other charges,2020,85,4.07,3.80,yes
1,Renault Kwid,RXT 0.8,77319,Petrol,Manual,UP,3804.0,₹1.80L₹1.71 L+ other charges,2016,80,1.80,1.71,yes
2,Maruti Swift,VDI ABS,87121,Diesel,Manual,HR,NaN,₹3.81L₹3.18 L+ other charges,2015,14,3.81,3.18,yes
3,Maruti Swift,LXI,66173,Petrol,Manual,HR,7432.0,₹4.37L₹4.21 L+ other charges,2022,14,4.37,4.21,yes
4,Renault Kwid,RXT 0.8,62135,Petrol,Manual,UP,2879.0,₹2.42L₹1.63 L+ other charges,2018,80,2.42,1.63,yes

In [43]:
df.dtypes

Cars                          object
Model                         object
Distance_in_km                 int64
Fuel                          object
Transmission                  object
Registration                  object
EMI_Per_Month                float64
Price                         object
Manufac_Year                   int64
Reg_unit                      object
Actual_Price_in_Lakhs        float64
Discounted_Price_in_Lakhs    float64
Price+Other_charges           object
dtype: object

In [47]:
df.drop(columns=["Price"],inplace=True)

In [48]:
df.head()

,Cars,Model,Distance_in_km,Fuel,Transmission,Registration,EMI_Per_Month,Manufac_Year,Reg_unit,Actual_Price_in_Lakhs,Discounted_Price_in_Lakhs
0,Maruti Swift,LXI,32750,Petrol,Manual,HR,6713.0,2020,85,4.07,3.80
1,Renault Kwid,RXT 0.8,77319,Petrol,Manual,UP,3804.0,2016,80,1.80,1.71
2,Maruti Swift,VDI ABS,87121,Diesel,Manual,HR,NaN,2015,14,3.81,3.18
3,Maruti Swift,LXI,66173,Petrol,Manual,HR,7432.0,2022,14,4.37,4.21
4,Renault Kwid,RXT 0.8,62135,Petrol,Manual,UP,2879.0,2018,80,2.42,1.63

In [49]:
df=df[["Cars","Model","Manufac_Year","Distance_in_km","Fuel","Transmission","Registration","Reg_unit","Actual_Price_in_Lakhs","Discounted_Price_in_Lakhs","EMI_Per_Month"]]

In [50]:
df

,Cars,Model,Manufac_Year,Distance_in_km,Fuel,Transmission,Registration,Reg_unit,Actual_Price_in_Lakhs,Discounted_Price_in_Lakhs,EMI_Per_Month
0,Maruti Swift,LXI,2020,32750,Petrol,Manual,HR,85,4.07,3.80,6713.0
1,Renault Kwid,RXT 0.8,2016,77319,Petrol,Manual,UP,80,1.80,1.71,3804.0
2,Maruti Swift,VDI ABS,2015,87121,Diesel,Manual,HR,14,3.81,3.18,NaN
3,Maruti Swift,LXI,2022,66173,Petrol,Manual,HR,14,4.37,4.21,7432.0
4,Renault Kwid,RXT 0.8,2018,62135,Petrol,Manual,UP,80,2.42,1.63,2879.0
5,Renault Kwid,RXT 0.8,2017,41654,Petrol,Manual,HR,79,2.50,1.50,2929.0
6,KIA SELTOS,HTK 1.5 PETROL,2022,43539,Petrol,Manual,HR,16,8.64,7.50,13243.0
7,Maruti Swift,VDI,2014,111698,Diesel,Manual,UP,16,2.92,1.98,NaN
8,Maruti New Wagon-R,VXI 1.2,2019,46641,Petrol,Manual,DL,2C,3.33,3.33,5886.0
9,Honda Amaze,1.2L I-VTEC VX,2018,63933,Petrol,Manual,DL,11,4.24,3.79,6690.0
10,Ford FREESTYLE,AMBIENTE 1.5 DIESEL,2019,55165,Diesel,Manual,UP,25,4.99,2.99,9931.0
11,Maruti Swift,LXI (O),2017,79321,Petrol,Manual,DL,8C,2.70,2.50,4886.0
12,Maruti Baleno,DELTA PETROL 1.2,2016,67702,Petrol,Manual,HR,26,3.21,3.21,7142.0
13,Toyota Glanza,S,2023,60527,Petrol,Manual,HR,26,5.64,5.00,8826.0
14,Skoda SLAVIA,AMBITION 1.0L TSI MT,2022,78434,Petrol,Manual,HR,44,11.13,7.64,13492.0
15,Hyundai Grand i10,SPORTZ 1.2 KAPPA VTVT,2016,82996,Petrol,Manual,HR,12,2.75,2.75,6123.0
16,Maruti Wagon R 1.0,LXI,2014,87492,Petrol,Manual,HR,52,2.23,1.38,4580.0
17,Maruti Baleno,ALPHA PETROL 1.2,2016,49803,Petrol,Manual,DL,12,3.71,3.50,7786.0
18,Tata NEXON,XZ PLUS (L) DARK EDITION,2022,55797,Petrol,Manual,UP,27,8.04,7.12,12569.0
19,Honda City,1.5L I-VTEC V MT,2016,58953,Petrol,Manual,HR,26,3.79,3.79,8441.0

In [52]:
df.to_csv("Cars24_cleaned_data.csv",index=False)